### ISSUE TITLE
Create automation for linking PRs with Issues

### ISSUE THREAD

**Issue by bwieckow** [Geeks-Academy/terraform#249]
this workflow has to be created

```
name: "Update Pull Request"
on:
  pull_request:
    types: [opened]

jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: tzkhan/pr-update-action@v2
      with:
        repo-token: "${{ secrets.PROJECTS_GITHUB_TOKEN }}"
        base-branch-regex: '[a-z\d-_.\\/]+'
        head-branch-regex: '#\d+'
        title-template: '[%headbranch%] '
        body-template: |
          Merging into '%basebranch%'
          Resolves %headbranch%
        body-update-action: 'suffix'
        body-uppercase-base-match: false
    
```

**Comment by bwieckow** [comment]
this workflow has to be created
```
name: "Update Pull Request"
on:
  pull_request:
    types: [opened]

jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: tzkhan/pr-update-action@v2
      with:
        repo-token: "${{ secrets.PROJECTS_GITHUB_TOKEN }}"
        base-branch-regex: '[a-z\d-_.\\/]+'
        head-branch-regex: '#\d+'
        title-template: '[%headbranch%] '
        body-template: |
          Merging into '%basebranch%'
          Resolves %headbranch%
        body-update-action: 'suffix'
        body-uppercase-base-match: false
    
```
